### ISSUE TITLE
Some proposals

### ISSUE THREAD

**Issue by Reneg973** [ms1963/SleepyPico#1]
I don't make a pull request as these are mostly not bugs, just improvements for readability/consistency.

- you may default the default constructor (Cpp feature, depends on which Cpp you want to support)
```
Sleep() = default;
```
- You may use function overloading
`void configure(MODE mode, ...);`
Here you could also use `std::function<>` instead of raw function ptrs.

- You may use const correctness:
`MODE get_mode() const;`

- You may order your MODE enum from no sleep to deepest sleep. Also `stdio_flush()` might be better for `printf()` than `uart_default_tx_wait_blocking();`

- Move headers which are not required for declaration to the implemenation. 

Also it is not very clear which kind of text format you use for which kind of types.

**Comment by Reneg973** [comment]
There is perhaps an issue with rtc.
I found out, that rtc_set_datetime() takes some time to set the value and it did not accept the next call to set an alarm. I am not sure whether this behavior is valid for sleep_goto_sleep_until() too.
And there is an assertion in sleep.c:
```
void sleep_goto_sleep_until(datetime_t *t, rtc_callback_t callback) {
    // We should have already called the sleep_run_from_dormant_source function
    assert(dormant_source_valid(_dormant_source));
```

which might assert because I don't see a call to `sleep_run_from_dormant_source()`. (maybe I'm wrong here)

**Comment by ms1963** [comment]
Dear Rene,

Thank you very much for your awesome suggestions.
All what you mentioned makes definitely sense. I will work on this soon.
Thanks for spending your time

Kind Regards 
   Michael 

Michael Stal, Auenstraße 34, 80469 München 
Principal Key Expert Engineer, SIEMENS
Editor-in-Chief, JavaSPEKTRUM 
Extraordinary Professor, University of Groningen

**Comment by Reneg973** [comment]
I am working on a small class library for Pico, but atm not for sleeping. May fit well into it.

And another tip, you can also modify your run function so, that you remove the else (just the else, not the _loop() call), then you can delete _loop() within _after_sleep().

**Comment by ms1963** [comment]
Dear Rene,

I made most of the changes. I’ll do the rest during the weekend.

Your library makes me curious. Looking forward to seeing it

Kind Regards
  Michael 

Michael Stal, Auenstraße 34, 80469 München 
Principal Key Expert Engineer, SIEMENS
Editor-in-Chief, JavaSPEKTRUM 
Extraordinary Professor, University of Groningen

**Comment by Reneg973** [comment]
Wow nice, looks very promising.

Developing this class library is a little bit sticky, as I think about everything, from naming to consistency to abstractness to usability to performance to compactness :) - and at the moment nobody for discussions.
Feel free to take a look, I made the repo public: https://github.com/Reneg973/PicoSPIDisplay. (I am also open for tips, ideas).
